[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
        "@chainlink/contracts-ccip/=lib/chainlink-ccip/chains/evm/",
        "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
        "@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/",
        "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
        "@chainlink/local/=lib/chainlink-local/",
        "@chainlink/policy-management/=lib/chainlink-ace/packages/policy-management/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
